/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Baldo
 */
public class MenuPenyedia extends javax.swing.JFrame {

    /**
     * Creates new form MenuPenyedia
     */
    public MenuPenyedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buatBarang = new javax.swing.JButton();
        daftarBarang = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PENYEDIA");

        buatBarang.setText("BUAT BARANG");

        daftarBarang.setText("DAFTAR BARANG");

        logout.setText("LOGOUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(daftarBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buatBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(logout)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(buatBarang)
                .addGap(18, 18, 18)
                .addComponent(daftarBarang)
                .addGap(53, 53, 53)
                .addComponent(logout)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatBarang;
    private javax.swing.JButton daftarBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the buatBarang
     */
    public javax.swing.JButton getBuatBarang() {
        return buatBarang;
    }

    /**
     * @param buatBarang the buatBarang to set
     */
    public void setBuatBarang(javax.swing.JButton buatBarang) {
        this.buatBarang = buatBarang;
    }

    /**
     * @return the daftarBarang
     */
    public javax.swing.JButton getDaftarBarang() {
        return daftarBarang;
    }

    /**
     * @param daftarBarang the daftarBarang to set
     */
    public void setDaftarBarang(javax.swing.JButton daftarBarang) {
        this.daftarBarang = daftarBarang;
    }

    /**
     * @return the logout
     */
    public javax.swing.JButton getLogout() {
        return logout;
    }

    /**
     * @param logout the logout to set
     */
    public void setLogout(javax.swing.JButton logout) {
        this.logout = logout;
    }

    public void addListener(ActionListener e){
        buatBarang.addActionListener(e);
        daftarBarang.addActionListener(e);
        logout.addActionListener(e);
    }
}
