/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author Baldo
 */
public class MenuPetugas extends javax.swing.JFrame {

    /**
     * Creates new form MenuPetugas
     */
    public MenuPetugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tambahBarang = new javax.swing.JButton();
        hapusBarang = new javax.swing.JButton();
        lihatGudang = new javax.swing.JButton();
        lihatSemuaBarang = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PETUGAS");

        tambahBarang.setText("TAMBAH BARANG");

        hapusBarang.setText("HAPUS BARANG");

        lihatGudang.setText("LIHAT GUDANG");

        lihatSemuaBarang.setText("LIHAT SEMUA BARANG");

        logout.setText("LOGOUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lihatGudang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lihatSemuaBarang)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(hapusBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tambahBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(logout)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(tambahBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapusBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatGudang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatSemuaBarang)
                .addGap(26, 26, 26)
                .addComponent(logout)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lihatGudang;
    private javax.swing.JButton lihatSemuaBarang;
    private javax.swing.JButton logout;
    private javax.swing.JButton tambahBarang;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the hapusBarang
     */
    public javax.swing.JButton getHapusBarang() {
        return hapusBarang;
    }

    /**
     * @param hapusBarang the hapusBarang to set
     */
    public void setHapusBarang(javax.swing.JButton hapusBarang) {
        this.hapusBarang = hapusBarang;
    }

    /**
     * @return the lihatGudang
     */
    public javax.swing.JButton getLihatGudang() {
        return lihatGudang;
    }

    /**
     * @param lihatGudang the lihatGudang to set
     */
    public void setLihatGudang(javax.swing.JButton lihatGudang) {
        this.lihatGudang = lihatGudang;
    }

    /**
     * @return the lihatSemuaBarang
     */
    public javax.swing.JButton getLihatSemuaBarang() {
        return lihatSemuaBarang;
    }

    /**
     * @param lihatSemuaBarang the lihatSemuaBarang to set
     */
    public void setLihatSemuaBarang(javax.swing.JButton lihatSemuaBarang) {
        this.lihatSemuaBarang = lihatSemuaBarang;
    }

    /**
     * @return the logout
     */
    public javax.swing.JButton getLogout() {
        return logout;
    }

    /**
     * @param logout the logout to set
     */
    public void setLogout(javax.swing.JButton logout) {
        this.logout = logout;
    }

    /**
     * @return the tambahBarang
     */
    public javax.swing.JButton getTambahBarang() {
        return tambahBarang;
    }

    /**
     * @param tambahBarang the tambahBarang to set
     */
    public void setTambahBarang(javax.swing.JButton tambahBarang) {
        this.tambahBarang = tambahBarang;
    }

    public void addListener(ActionListener e){
        tambahBarang.addActionListener(e);
        hapusBarang.addActionListener(e);
        lihatGudang.addActionListener(e);
        lihatSemuaBarang.addActionListener(e);
        logout.addActionListener(e);
    }
}
